void glViewport(int x, int y, int width, int height);
void glClearColor(float r, float g, float b, float a);
void glClear(unsigned int mask);
unsigned int glGetError(void);
unsigned int glCreateShader(unsigned int shaderType);
void glShaderSource(unsigned int shader, int count, const char** string, const int* length);
void glCompileShader(unsigned int shader);
void glGetShaderiv(unsigned int shader, unsigned int pname, int* params);
void glGetShaderInfoLog(unsigned int shader, int maxLength, int* length, char* infoLog);
void glDeleteShader(unsigned int shader);
unsigned int glCreateProgram(void);
void glAttachShader(unsigned int program, unsigned int shader);
void glLinkProgram(unsigned int program);
void glGetProgramiv(unsigned int program, unsigned int pname, int* params);
void glGetProgramInfoLog(unsigned int program, int maxLength, int* length, char* infoLog);
void glUseProgram(unsigned int program);
void glDeleteProgram(unsigned int program);
void glGenVertexArrays(int n, unsigned int* arrays);
void glBindVertexArray(unsigned int array);
void glDeleteVertexArrays(int n, const unsigned int* arrays);
void glGenBuffers(int n, unsigned int* buffers);
void glBindBuffer(unsigned int target, unsigned int buffer);
void glBufferData(unsigned int target, long size, const void* data, unsigned int usage);
void glDeleteBuffers(int n, const unsigned int* buffers);
void glEnableVertexAttribArray(unsigned int index);
void glVertexAttribPointer(unsigned int index, int size, unsigned int type, unsigned char normalized, int stride, const void* pointer);
int glGetUniformLocation(unsigned int program, const char* name);
void glUniformMatrix4fv(int location, int count, unsigned char transpose, const float* value);
void glUniform1i(int location, int value);
void glUniform1f(int location, float value);
void glUniform2f(int location, float v0, float v1);
void glUniform3f(int location, float v0, float v1, float v2);
void glUniform4f(int location, float v0, float v1, float v2, float v3);
void glGenTextures(int n, unsigned int* textures);
void glBindTexture(unsigned int target, unsigned int texture);
void glTexParameteri(unsigned int target, unsigned int pname, int param);
void glTexImage2D(unsigned int target, int level, int internalformat, int width, int height, int border, unsigned int format, unsigned int type, const void* pixels);
void glGenerateMipmap(unsigned int target);
void glActiveTexture(unsigned int texture);
void glDeleteTextures(int n, const unsigned int* textures);
void glDrawArrays(unsigned int mode, int first, int count);
void glDrawElements(unsigned int mode, int count, unsigned int type, const void* indices);
void glEnable(unsigned int cap);
void glDisable(unsigned int cap);
